### ISSUE TITLE
Google SERP still displaying "the Bitsquare Forum"

### ISSUE THREAD

**Issue by Mycelial1** [bisq-network/forum#10]
The google search results for "Bisq forum" still displays "Bitsquare" as shown in the attached screenshot.
It should be changed to "the Bisq Forum".

![forum](https://user-images.githubusercontent.com/34950746/58713578-db57bb80-8390-11e9-88fd-ac31ce0c33f1.PNG)

**Comment by alexej996** [comment]
I am not sure where Google gets this data from, but it seems like it is not from the current version of our forum.

Doesn't look like we can do much about it now honestly. Maybe using some Google's website administration services could help, but I really try to avoid using anything from Google when possible.

**Comment by alexej996** [comment]
I think Google updated it's cache. I can't check directly since Google is not friendly to Tor, but startpage seems to disply it correctly and as far as I know it uses Google API for it's searches.
