### ISSUE TITLE
Make links stand out better

### ISSUE THREAD

**Issue by m52go** [bisq-network/forum#12]
Right now links on the forum look just like regular text, so it's almost impossible to know if/where links exist.

Could we change the text color, add an underline, or add some kind of visual cue to make links more obvious?

**Comment by alexej996** [comment]
Links should be blue compared to black text. They should also glow when you move a mouse over them. Does it show differently to you?

I can change the color if you want of course.

This is what it looks like to me:

![forum_links](https://user-images.githubusercontent.com/24721710/64603829-7dd00380-d3b0-11e9-9a2e-110f86f0d0b6.png)

**Comment by m52go** [comment]
Ah, I had a filter on my monitor that adjusted the color temperature and gamma to make links blend in.

I do think link colors could be a little brighter / higher contrast, but it's nothing urgent/extreme as I mentioned in my first post. 

Sorry!
