### ISSUE TITLE
Forums source code is missing

### ISSUE THREAD

**Issue by wiz** [bisq-network/forum#13]
Why is the source code of the forums not in this repo? Is it hosted elsewhere? How do we make changes?

**Comment by alexej996** [comment]
Forum uses Discourse forum software. You can find the source code at https://github.com/discourse/discourse , but we did not make a fork of it to make changes.

Discourse provides some customization options form the admin menu, so we usually change headers and CSS from the web admin page there.

**Comment by wiz** [comment]
so we should submit PRs to the main discourse repo? why no bisq fork?

**Comment by alexej996** [comment]
I don't know. If someone wants to create a fork on Bisq's github account, I have no issues with it.
