### ISSUE TITLE
Set up Discourse->Slack plugin

### ISSUE THREAD

**Issue by cbeams** [bisq-network/forum#2]
Doing this will help the team monitor what's going on in the forum from within Slack. One stop shopping, and all that.

- [ ] Get our Discourse Docker configuration set up in bitsquare/forum repo (if possible)
- [ ] Install and configure the https://github.com/discourse/discourse-slack-official plugin such that new threads / posts show up in our #forum Slack channel

**Comment by cbeams** [comment]
See https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

**Comment by alexej996** [comment]
Repository for this plugin states that it is no longer supported.
Instead it links to a new repo at https://github.com/discourse/discourse-chat-integration

I will look into this when I have a bit more time later.

**Comment by alexej996** [comment]
We moved to keybase, not sure if this is still needed.
