### ISSUE TITLE
Pegging order exchange rate to "market price" opens the maker to abuse

### ISSUE THREAD

**Issue by menkaur** [bisq-network/forum#9]
There probably is a good reason why this option was added to Bisq, but also there is a very good reason why none of the standard exchanges ever does something like this.

Let's assume that the maker is a buyer for this explanation

First of all,  "market price" +- 2% means that anyone can sell to to the maker at whatever the market price is +2%. Correct me if i'm wrong. If there are multiple "market price" providers, the taker is free to choose the price he likes best on top of that

Another issue is that the "market price" is really easy to manipulate, especially on thin markets. You just have to figure out the algorithm that the "market price" providers use to get their numbers (usually some sort of close, tick value or top bid/ask, or some sort of moving average in the worst case). After that, the taker can get very nice discounts on taking the orders pegged to the "market price".

One possible solution to this is shifting the burden of finding the "market price" from the network to the peer itself. The taker would have to connect to the maker and negotiate what the "market price" is before the offer can be taken

**Comment by ghost** [comment]
In the last 4 months, I didn't remember any complaint concerning such a case.

**Comment by menkaur** [comment]
you can treat this as vulnerability report. the fact that it's not used now does not mean that it's not going to cost people money in the future

**Comment by alexej996** [comment]
Although I share your concern about price manipulation, I am not sure that negotiation with the other peer about the price is something that would be better then just setting up a fixed price offer instead.

I am not totally sure how market price is provided, but as I understand, there are special nodes that contributors can run that are relaying prices from multiple price providers such as BitcoinAverage.

Either way, this is a forum repository, there is probably a better place for this. This repo was made mainly to track issues that are connected to the Bisq forum.
Probably the best place for this is [proposals](https://github.com/bisq-network/proposals) repo or maybe even [price node](https://github.com/bisq-network/bisq-pricenode) repository.

I would consider talking about this on Slack though or maybe opening a new topic about it on the forum.
